# Generated by Django 4.2.5 on 2025-01-03 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0015_patient_histopath_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='height',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be negative.')]),
        ),
    ]
