# Generated by Django 4.2.5 on 2025-01-03 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0016_alter_physicalexam_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='ecog_score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative'), django.core.validators.MaxValueValidator(5, message='Value cannot be above 5')]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='height',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='hr',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='pain_score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative'), django.core.validators.MaxValueValidator(10, message='Value cannot be above 10')]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='weight',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
    ]
