# Generated by Django 4.2.5 on 2025-01-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0019_alter_screening_gapsma_bone_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
