# Generated by Django 4.2.5 on 2025-01-04 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0020_alter_physicalexam_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalexam',
            name='ecog_score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0, message='Value should be 0-5'), django.core.validators.MaxValueValidator(5, message='Value should be 0-5')]),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='pain_score',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0, message='Value should be 0-10'), django.core.validators.MaxValueValidator(10, message='Value should be 0-10')]),
        ),
    ]
