# Generated by Django 5.1.4 on 2025-01-04 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0021_alter_physicalexam_ecog_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_bone_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Bone Lesion Size'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_bone_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Bone SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_brain_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Brain Lesion Size'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_brain_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Brain SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_liver_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Liver Lesion Size'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_liver_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Liver SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lung_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Lung Lesion Size'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lung_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Lung SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lymph_node_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Lymph Node Lesion Size'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_lymph_node_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Lymph Node SUV'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_prostate_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Prostate Lesion Size'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='fdgpetct_prostate_suv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative')], verbose_name='Prostate SUV'),
        ),
    ]
