# Generated by Django 5.1.4 on 2025-01-04 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0007_alter_posttherapy_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='kidney_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='kidney_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='post_therapy_scan_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='posttherapy',
            name='salivary_gland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
