# Generated by Django 4.2.5 on 2025-01-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0008_alter_posttherapy_kidney_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttherapy',
            name='dosimetry_image',
        ),
        migrations.RemoveField(
            model_name='posttherapy',
            name='lesion_image',
        ),
        migrations.CreateModel(
            name='LesionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lesion_images/')),
                ('post_therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_images', to='part_3.posttherapy')),
            ],
        ),
        migrations.CreateModel(
            name='DosimetryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dosimetry_images/')),
                ('post_therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosimetry_images', to='part_3.posttherapy')),
            ],
        ),
    ]
