# Generated by Django 4.2.5 on 2025-01-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0023_alter_patient_age_alter_patient_gleason_score'),
        ('part_3', '0009_remove_posttherapy_dosimetry_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_therapies', to='part_1.patient'),
        ),
    ]
