# Generated by Django 4.2.5 on 2025-01-04 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0010_alter_posttherapy_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttherapy',
            name='post_therapy_scan_hours',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Value cannot be zero or negative.')]),
        ),
    ]
