# Generated by Django 4.2.5 on 2025-01-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0011_alter_posttherapy_post_therapy_scan_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosimetryimage',
            name='post_therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosimetry_image_set', to='part_3.posttherapy'),
        ),
        migrations.AlterField(
            model_name='lesionimage',
            name='post_therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_image_set', to='part_3.posttherapy'),
        ),
    ]
