# Generated by Django 5.1.4 on 2025-01-04 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0004_alter_therapy_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='hr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='rr',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='saturation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0, message='SValue cannot be zero or negative.')]),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='systolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value cannot be zero or negative.')]),
        ),
    ]
