# Generated by Django 5.1.4 on 2025-01-04 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0005_alter_therapy_diastolic_alter_therapy_hr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='saturation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0, message='Value cannot be zero or negative.')]),
        ),
    ]
